services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USERNAME=postgres
      - POSTGRES_PASSWORD=Postgres2024!
      - HOST=postgres
      - DATABASE=project
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "Postgres2024!"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "project"
    ports:
      - "5432:5432"
volumes:
  data: