apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
  labels:
    app: api-backend
spec:
  template:
    metadata:
      labels: 
        app: api-backend-deploy
    spec:
      containers:
        - name: api-container
          image: api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
  replicas: 1
  selector:
    matchLabels:
      app: api-backend-deploy

---
apiVersion: v1
kind: Service
metadata:
  name: outside-api
  namespace: api
spec:
  type: NodePort
  selector: 
    app: api-backend-deploy
  ports:
    - port: 8080
      nodePort: 30001
