apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: svc-postgres
spec:
  ports:
    - name: port-postgres
      port: 5432
      
  clusterIP: None
  selector:
    app: postgres-pod

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: api
  name: postgres-statefulset
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-pod
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: secret-postgres
          env:
            - name: POSTGRES_DB
              value: project

          volumeMounts:
            - name: volume-persistente-postgres
              mountPath: /var/lib/postgresql/data
  selector:
    matchLabels:
      app: postgres-pod
  serviceName: "svc-postgres"
  volumeClaimTemplates:
    - metadata:
        name: volume-persistente-postgres
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi